server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: arun
  application:
    name: HOTEL-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
       format_sql: true

  config:
    import: optional:configserver://localhost:8085

okta:
  oauth2:
    issuer: https://dev-34551137.okta.com/oauth2/default
    audience: api://default

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
