
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false


#  server.port=5000
#    spring.application.name=discovery-service
#    eureka.client.fetch-registry=false
#    eureka.client.register-with-eureka=false
#
#    eureka.instance.hostname=localhost
#    eureka.client.service-url.defaultZone = http://localhost:5000/eureka/
#